server {
    listen 80;
    server_name f-suite.com www.f-suite.com;

    root /var/www/f-suite-landing/build;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    error_log /var/log/nginx/f-suite.error.log;
    access_log /var/log/nginx/f-suite.access.log;
}
